import { useNavigate, useParams } from 'react-router-dom'
import { useState } from 'react'
import { FiArrowLeft, FiBookOpen, FiHeart, FiShare2, FiBookmark, FiDownload, FiClock } from 'react-icons/fi'
import { useLibrary } from '../context/LibraryContext'
import { downloadDocument } from '../services/api'

function BookDetails(){
 const {id}=useParams(); const navigate=useNavigate(); const {books,loading}=useLibrary(); const [downloading,setDownloading]=useState(false); const book=books.find(item=>String(item.id)===String(id))
 if(loading&&!book)return <div className="empty-library"><h3>Chargement du livre…</h3></div>
 if(!book)return <div className="book-not-found"><div className="book-not-found-icon"><FiBookOpen/></div><h1>Livre introuvable</h1><p>Le livre n'est pas disponible dans l'API.</p><button onClick={()=>navigate('/bibliotheque')}><FiArrowLeft/>Retour</button></div>
 const handleDownload=async()=>{try{setDownloading(true); const blob=await downloadDocument(book.id); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`${book.title||'document'}.pdf`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url)}catch(e){window.alert(e.message||'Téléchargement impossible.')}finally{setDownloading(false)}}
 return <div className="book-details-page"><button className="back-button" onClick={()=>navigate('/bibliotheque')}><FiArrowLeft/>Retour à la bibliothèque</button><section className="book-details-main"><div className="book-details-cover"><div className="book-details-cover-inner"><FiBookOpen/><strong>CONGOLIBS</strong><span>LIVRE</span></div></div><div className="book-details-info"><span className="book-details-category">LIVRE</span><h1>{book.title}</h1><p className="book-details-author">Par <strong>{book.author}</strong></p><p className="book-description">Cette fiche utilise les informations enregistrées dans l'API CONGOLIBS. Le fichier e-book est récupéré depuis le service de téléchargement sécurisé.</p><div className="book-details-stats"><div className="book-stat"><FiBookOpen/><div><strong>PDF</strong><span>Format</span></div></div><div className="book-stat"><FiClock/><div><strong>{book.date?new Date(book.date).toLocaleDateString('fr-FR'):'—'}</strong><span>Ajouté</span></div></div></div><div className="book-details-actions"><button className="read-book-button" onClick={()=>navigate(`/lecteur/${book.id}`)}><FiBookOpen/>Lire / consulter</button><button className="read-book-button" onClick={handleDownload} disabled={downloading}><FiDownload/>{downloading?'Téléchargement…':'Télécharger'}</button><button className="secondary-book-button"><FiHeart/></button><button className="secondary-book-button"><FiBookmark/></button><button className="secondary-book-button on-click" onClick={()=>navigator.clipboard?.writeText(window.location.href)}><FiShare2/></button></div></div></section><section className="book-description-section"><div className="book-section-heading"><span className="section-label">À PROPOS DU LIVRE</span><h2>Présentation</h2></div><div className="book-long-description"><p><strong>{book.title}</strong> est enregistré dans la bibliothèque numérique CONGOLIBS.</p><p>L'accès au fichier est relié directement à l'endpoint de téléchargement du Backend de ton équipe.</p></div></section></div>
}
export default BookDetails
